### ISSUE TITLE
lab3 lab4 lab5 编译报错

### ISSUE THREAD

**Issue by Zony-Zhao** [woai3c/MIT6.828#2]
![image](https://user-images.githubusercontent.com/50739849/183879629-361ed322-e16c-4b25-a93d-2ab1e79bfd4a.png)
![image](https://user-images.githubusercontent.com/50739849/183879667-c6a98dfe-50a2-43b0-878c-2f00b1eb7c9b.png)

![image](https://user-images.githubusercontent.com/50739849/183879701-afef8c38-6fd4-49b0-bd7e-37134c8f4ac1.png)

**Comment by woai3c** [comment]
这个我也不太懂，得网上搜搜了。
