### ISSUE TITLE
滴滴，参考资料都失效了

### ISSUE THREAD

**Issue by msgui** [woai3c/MIT6.828#3]

**Comment by msgui** [comment]
![image](https://user-images.githubusercontent.com/87920097/222907514-9cd45a9a-3fb5-410e-a6af-e8e6ed596752.png)

**Comment by woai3c** [comment]
* [x86汇编语言:从实模式到保护模式](https://book.douban.com/subject/20492528/)
* [xv6-chinese](https://github.com/ranxian/xv6-chinese)
* [操作系统导论](https://book.douban.com/subject/33463930/)或任意一本操作系统书籍

更新了一下链接
