### ISSUE TITLE
编译

### ISSUE THREAD

**Issue by maitianshouwangzhe3** [woai3c/MIT6.828#4]
你编译这个内核的系统是ubuntu吗，版本是多少？我这边编译qemu报错，显示glib那边出问题了

**Comment by woai3c** [comment]
我用的是 18 版本，安装环境确实是很困难的一步。我在两台电脑上都装过环境，遇到的报错都不一样，只能每次根据报错信息去网上查找解决方案。其实网上很多人分享的成功安装环境的教程，你会发现里面有些报错也是不一样的。所以只能每次根据不同的报错信息去查答案。

**Comment by maitianshouwangzhe3** [comment]
好的，我解决了，就是依赖版本问题，我用ubuntu16可以直接编译过，不会有任何报错，使用高版本系统就会出各种各样的问题
